[package]
name = "razen-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift = "0.104.1"
cranelift-module = "0.104.1"
cranelift-jit = "0.104.1"
cranelift-native = "0.104.1"
cranelift-frontend = "0.104.1"
cranelift-object = "0.104.1"
