[package]
name = "razen-lang"
version = "0.1.4"
edition = "2024"

[dependencies]
# Professional CLI with minimal, well-maintained dependencies
clap = { version = "4.4", features = ["derive", "color"] }

[dev-dependencies]
# No dev dependencies needed for now
