[package]
name = "razen-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
# Clean, minimal dependencies for our from-scratch implementation

[dev-dependencies]
# No dev dependencies needed for now
