id = "razen"
name = "Razen"
version = "0.1.0"
schema_version = 1
description = "Language support for Razen - a modern, efficient programming language"
repository = "https://github.com/BasaiCorp/Razen-New"
authors = ["Razen Language Team <razen@example.com>"]
themes = []
languages = ["languages/razen"]

[lib]

[grammars.razen]
repository = "https://github.com/BasaiCorp/Razen-New"
rev = "0ec718dc4f2fbc5dc3847687e18c2c3e8bd19758"
path = "extensions/razen-zed/tree-sitter-razen"

[language_servers]

[slash_commands]
