[package]
name = "tree-sitter-razen"
version = "0.1.0"
description = "Tree-sitter grammar for Razen"
authors = ["Razen Language Team"]
license = "MIT"
edition = "2021"

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20"

[build-dependencies]
cc = "1.0"
